#!/usr/bin/env node

const rt = require("./rt");

rt.async_raiilock(async function () {
    const token = rt.argv().module;
    rt.assert(token, "no pass option: -m | --module");

    const deployedCollateral = rt.get("Collateral");
    rt.log("get Collateral:", JSON.stringify(deployedCollateral, null, 4));

    const collateralAddress = deployedCollateral && deployedCollateral[token];
    rt.assert(collateralAddress, `not find Collateral(${token})`);

    let ove = rt.configure().tokens[token].init.ove;
    rt.log(`get 'tokens[${token}].init.ove': `, ove);

    ove = ove / 100;
    ove = rt.web3().utils.toWei(ove.toString(), 'ether').toString();
    rt.log(`Collateral.methods.setove(ove = ${ove})`);

    let Collateral = await rt.rt_contract_at("Collateral", collateralAddress);
    const tx = Collateral.methods.setove(ove);
    await rt.send(tx, collateralAddress);
});