#!/usr/bin/env node

const rt = require("./rt");

rt.async_raiilock(async function () {
    const token = rt.argv().module;
    rt.assert(token, "no pass option: -m | --module");

    const deployedCollateral = rt.get("Collateral");
    rt.log("get Collateral:", JSON.stringify(deployedCollateral, null, 4));

    const collateraladdress = deployedCollateral && deployedCollateral[token];
    rt.assert(collateraladdress, `not find collateral(${token})`);

    let seg = rt.configure().tokens[token].init.seg;
    rt.log(`get 'tokens[${token}].init.seg': `, seg);

    seg = rt.web3().utils.toWei(seg.toString(), 'ether').toString();
    rt.log(`Collateral.methods.setseg(seg = ${seg})`);

    let Collateral = await rt.rt_contract_at("Collateral", collateraladdress);
    const tx = Collateral.methods.setseg(seg);
    await rt.send(tx, collateraladdress);
});