#!/usr/bin/env node

const rt = require("./rt");

rt.async_raiilock(async function () {
    const token = rt.argv().module;
    rt.assert(token, "no pass option: -m | --module");

    const deployedCollateral = rt.get("Collateral");
    rt.log("get Collateral:", JSON.stringify(deployedCollateral, null, 4));

    const collateralAddress = deployedCollateral && deployedCollateral[token];
    rt.assert(collateralAddress, `not find Collateral(${token})`);

    let fin = rt.configure().tokens[token].init.fin;
    rt.log(`get 'tokens[${token}].init.fin': `, fin);
    
    fin = fin / 100;
    fin = rt.web3().utils.toWei(fin.toString(), 'ether').toString();
    rt.log(`Collateral.methods.setfin(fin = ${fin})`);

    let Collateral = await rt.rt_contract_at("Collateral", collateralAddress);
    const tx = Collateral.methods.setfin(fin);
    await rt.send(tx, collateralAddress);
});