#!/usr/bin/env node

const rt = require("./rt");

rt.async_raiilock(async function () {

    const deployedCollateral = rt.get("Collateral");
    rt.log("get Collateral:", JSON.stringify(deployedCollateral, null, 4));

    const tokens = rt.gettokens();
    for (let i = 0; i < tokens.length; ++i) {
        const token = tokens[i].symbol;

        const collateralAddress = deployedCollateral && deployedCollateral[token];
        rt.assert(collateralAddress, `not find Collateral(${token})`);

        const configure = rt.configure()['government']['collateral'][token];
        rt.assert(configure, `no get 'government.collateral.${token}'`);

        let gth = configure.gth;
        rt.assert(gth == 0 || gth, `no get 'government.collateral.${token}.gth'`);
        rt.log(`get 'government.collateral.${token}.gth': `, gth);

        //duty=$(bc -l <<< "scale=27; e( l(2.5 / 100 + 1)/(60 * 60 * 24 * 365)) * 10^27")
        gth = Math.log(gth / 100 + 1) / (60 * 60 * 24 * 365);
        gth = 1e18 * Math.E ** gth;
        gth = gth.toString();
        rt.log(`Collateral.methods.setgth(gth = ${gth})`);

        let Collateral = await rt.rt_contract_at("Collateral", collateralAddress);
        const tx = Collateral.methods.setgth(gth);
        await rt.send(tx, collateralAddress);
    }
});