#!/usr/bin/env node

const rt = require("./rt");

rt.async_raiilock(async function () {
    const token = rt.argv().module;
    rt.assert(token, "no pass option: -m | --module");

    const deployedCollateral = rt.get("Collateral");
    rt.log("get collateral:", JSON.stringify(deployedCollateral, null, 4));
  
    const collateralAddress = deployedCollateral && deployedCollateral[token];
    rt.assert(collateralAddress, `not find Collateral(${token})`);

    const low = rt.configure().tokens[token].init.low;
    rt.log(`get 'tokens[${token}].init.low':`, low);

    rt.log(`Collateral.methods.setlow(low = ${low})`);

    let Collateral = await rt.rt_contract_at("Collateral", collateralAddress);
    const tx = Collateral.methods.setlow(low);
    await rt.send(tx, collateralAddress);
});