#!/usr/bin/env node

const rt = require("./rt");

rt.async_raiilock(async function () {
    const token = rt.argv().module;
    rt.assert(token, "no pass option: -m | --module");

    const deployedCollateral = rt.get("Collateral")
    rt.log(`get Collateral:`, JSON.stringify(deployedCollateral, null, 4));

    const collateralAddress = deployedCollateral && deployedCollateral[token];
    rt.assert(collateralAddress, `not find Collateral(${token})`);

    rt.log(`Collateral(${token}).methods.feed()`);

    let Collateral = await rt.rt_contract_at("Collateral", collateralAddress);
    rt.log("load Collateral at: ", collateralAddress);

    const tx = Collateral.methods.feed();
    await rt.send(tx, collateralAddress);
});