#!/usr/bin/env node

const rt = require("./rt");

rt.async_raiilock(async function () {
    const token = rt.argv().module;
    rt.assert(token, "no pass option: -m | --module");

    const deployedCollateral = rt.get("Collateral");
    rt.log("get Collateral:", JSON.stringify(deployedCollateral, null, 4));

    const collateralAddress = deployedCollateral && deployedCollateral[token];
    rt.assert(collateralAddress, `not find collateral(${token})`);

    let upp = rt.configure().tokens[token].init.upp;
    rt.log(`get 'tokens[${token}].init.upp': `, upp);

    upp = rt.web3().utils.toWei(upp.toString(), 'ether').toString();
    rt.log(`Collateral.methods.setupp(upp = ${upp})`);

    let Collateral = await rt.rt_contract_at("Collateral", collateralAddress);
    const tx = Collateral.methods.setupp(upp);
    await rt.send(tx, collateralAddress);
});