#!/usr/bin/env node

const rt = require("./rt");

rt.async_raiilock(async function() {
    
    const debtorAddress = rt.get("Debtor");
    rt.log("get Debtor:", debtorAddress);

    const configure = rt.configure()['government']['debtor'];
    rt.assert(configure, `no get 'government.debtor'`);

    let tdc = configure.tdc;
    rt.assert(tdc == 0 || tdc, `no get 'government.debtor.tdc'`);
    rt.log(`get 'government.debtor.tdc': `, tdc);

    tdc = rt.web3().utils.toWei(tdc.toString(), 'ether').toString();
    rt.log("Debtor.methods.settdc: ", tdc);
    
    let Debtor = await rt.rt_contract_at("Debtor", debtorAddress);
    const tx = Debtor.methods.settdc(tdc);
    await rt.send(tx, debtorAddress);
});