#!/usr/bin/env node

const rt = require("./rt");

rt.async_raiilock(async function() {
    rt.log("deploy Govauction...");

    const Wallet = rt.get("Wallet");
    rt.log("get Wallet: ", Wallet);

    const Govauction = await rt.rt_contract_new("Govauction", Wallet);
    rt.log("deploy Govauction at: ", Govauction.options.address);
    rt.set("Govauction", Govauction.options.address);
});