#!/usr/bin/env node

const rt = require("./rt");

rt.async_raiilock(async function() {
    rt.log("deploy Liquidauction...");

    const Wallet = rt.get("Wallet");
    rt.log("get Wallet: ", Wallet);

    const Liquidauction = await rt.rt_contract_new("Liquidauction", Wallet);
    rt.log("deploy Liquidauction at: ", Liquidauction.options.address);
    rt.set("Liquidauction", Liquidauction.options.address);
});