#!/usr/bin/env node

const rt = require("./rt");

//喂价器
rt.async_raiilock(async function() {
    const value = {};
    const ctokens = rt.getctokens();
    for(let i = 0; i < ctokens.length; ++i) {
        const symbol = ctokens[i].symbol.toUpperCase();
        rt.log(`deploy feeder(${symbol})...`);
        const feeder = await rt.rt_contract_new("feeder");
        rt.log(`deploy feeder(${symbol}) at: `, feeder.options.address);

        value[symbol] = feeder.options.address;
    }
    rt.set("feeder", value);
});
