#!/usr/bin/env node

const rt = require("./rt");

//治理代币合约
rt.async_raiilock(async function() {
    rt.log("deploy Govtoken...");
    //{symbol: "FOR", address: "0x..."}
    const fortoken = rt.configure().govtoken;
    rt.assert(fortoken, "not find 'FOR' token address");
    rt.log("find 'FOR' token: ", fortoken);
    const Govtoken = await rt.rt_contract_new("Govtoken", fortoken.address);
    rt.log("deploy Govtoken: ", Govtoken.options.address);
    rt.set("Govtoken", Govtoken.options.address);
});
