#!/usr/bin/env node

const rt = require("./rt");

//喂价器
rt.async_raiilock(async function() {
    const symbol = rt.argv().module;
    rt.assert(symbol, "no pass option: -m | --module");

    rt.log(`deploy Feeder(${symbol})...`);

    const value = rt.get('Feeder') || {};
    rt.log("get Feeder: ", value);

    const Feeder = await rt.rt_contract_new("Feeder");
    rt.log(`deploy Feeder(${symbol}) at: `, Feeder.options.address);

    value[symbol] = Feeder.options.address;
    rt.set("Feeder", value);
});
