#!/usr/bin/env node

const rt = require("./rt");

//ERC20抵押支持
rt.async_raiilock(async function() {
    rt.log(`deploy Wallet...`);

    const Wallet = await rt.rt_contract_new("Wallet");
    rt.log(`deploy Wallet at: `, Wallet.options.address);
    const walletAddress = Wallet.options.address;

    const tokens = rt.configure().tokens;
    const symbols = Object.keys(tokens);

    for(const symbol of symbols) {
        const address = tokens[symbol].address;
        rt.log(`Wallet.create(address = ${address}`);
        const tx = Wallet.methods.create(address);
        await rt.send(tx, walletAddress);
    }

    const Stablecoin = rt.get("Stablecoin");
    rt.log("get Stablecoin: ", Stablecoin);

    let tx = Wallet.methods.create(Stablecoin);
    await rt.send(tx, walletAddress);

    const Govtoken = rt.get("Govtoken");
    rt.log("get Govtoken: ", Govtoken);
    tx = Wallet.methods.join(Govtoken);
    await rt.send(tx, walletAddress);

    rt.set(`Wallet`, walletAddress);
});