#!/usr/bin/env node

const rt = require("./rt");

//稳定币token
rt.async_raiilock(async function() {
    rt.log("deploy Stablecoin...");
    const Stablecoin = await rt.rt_contract_new("Stablecoin", "THE FORCE PROTOCOL STABLECOIN", "QIAN", 18);
    rt.log("deploy Stablecoin at: ", Stablecoin.options.address);
    rt.set("Stablecoin", Stablecoin.options.address);
});