#!/usr/bin/env node

const rt = require("./rt");

rt.async_raiilock(async function() {
    const output = `${process.env.PWD}/${rt.rt_conf.network}.address.json`;
    rt.log("export to: ", output);
    rt.export(output);
});