#!/usr/bin/env node

const rt = require("./rt");

rt.async_raiilock(async function() {
    const token = rt.argv().module;
    rt.assert(token, "no pass option: -m | --module");

    const deployedFeeder = rt.get("Feeder");
    rt.log('get Feeder:', JSON.stringify(deployedFeeder, null, 4));

    const feederAddress = deployedFeeder && deployedFeeder[token];
    rt.assert(feederAddress, `not find Feeder(${token}`);
    let Feeder = await rt.rt_contract_at("Feeder", feederAddress);
    
    const pce = rt.configure().mock.feeder[token].init.pce;
    rt.log(`get 'mock.feeder[${token}].pce': `, pce);
    
    const val = rt.web3().utils.toWei(String(pce)).toString();
    const exp = String(360000);
    rt.log(`Feeder.set(val = ${val}, exp = ${exp})`);

    const tx = Feeder.methods.set(val, exp);
    await rt.send(tx, feederAddress);
});