#!/usr/bin/env node

const rt = require("./rt");

//token: USDT, DAI, TES, ...
const argv = rt.yargs()
    .options('token', {
        alias: 't',
        describe: 'The symbol of the token collateral',
        type: 'string'
    })
    .argv;

rt.async_raiilock(async function() {
    const token = argv.token;

    rt.assert(token, "missing option: --token | -t");
    
    const deployedctoken = rt.get("ctoken")
    rt.log(`get ctoken:`, 
        JSON.stringify(deployedctoken, null, 4));
    
    const ctokenaddress = deployedctoken && deployedctoken[token];
    rt.assert(ctokenaddress, `not find ctoken(${token})`);

    const testokenaddress = "0x3D81b11281E15838940F207520d8bA356E668445";
    const amount = "100000000000000000000000000";

    rt.log(`testoken.methods.approve(who = ${ctokenaddress}, amount = ${amount})`);

    const testoken = rt.rt_contract_at("stderc20", testokenaddress);
    tx = testoken.methods.approve(ctokenaddress, amount);
    await rt.send(tx, testokenaddress);
});
